baseURL = "https://dannywolfmx.github.io/video/"
languageCode = "es"
title = "NueTube"

[params]
  description = ""
  author = "Daniel"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1
